### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by keprt** [NIVeriStandAdd-Ons/Custom-Device-XML-Editor#2]
There is missing source code.
@tannerblair could you please update?

**Comment by MichaelAivaliotis** [comment]
Is this project dead?

**Comment by tannerblair** [comment]
It's not actively developed, and isn't super-stable. I'll push what we have internally so it can be accessed here.

**Comment by AndrewHeim** [comment]
I would say that although it's not perfect, it is still potentially very useful.  Take care to use the same version of LabVIEW and VeriStand and you should avoid issues.
